import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import LotteryEntrance from "../components/LotteryEntrance";
import { useAccount } from 'wagmi'
import { mainnet, sepolia, baseSepolia } from '@wagmi/core/chains'
import Wrapper2 from "../components/Wrapper2"
import NFTBoxContainer from "../components/ownedNfts"


export default function Home() {

  const { address, isConnecting, isConnected, isDisconnected } = useAccount()
  return (
    <div className="bg-slate-950 min-h-screen" >
      <Head>
        <title>DrawProof</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="flex justify-evenly items-center">
        <Wrapper2 />
        {isConnected ? (
          <div>
            {baseSepolia ? (
              <div className="">
                <LotteryEntrance className="p-8" />
              </div>
            ) : (
              <div>{`Please switch to BASE Sepolia to see the Raffle...`}</div>
            )}
          </div>
        ) : (
          <div className="text-xl font-semibold tracking-tight text-gray-900 dark:text-white mb-2" >Please connect to a Wallet</div>
        )}
      </div>
      <NFTBoxContainer />

      <footer className="bg-white rounded-lg shadow dark:bg-gray-900 m-4">
        <div className="w-full max-w-screen-xl mx-auto p-4 md:py-8">
          <div className="sm:flex sm:items-center sm:justify-between">
            <span className="flex items-center mb-4 sm:mb-0 space-x-3 rtl:space-x-reverse">
              <img src="https://i.ibb.co/bPMZbSf/team-rocket-logo-32.png" className="h-8" alt="Flowbite Logo" />
              <span className="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">RocketTeam</span>
            </span>

          </div>
          <hr className="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />
          <span className="block text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2024 RocketTeam. All Rights Reserved.</span>
        </div>
      </footer>
    </div>


  );
}
